### PR TITLE
Migrate to rebar3 and use hackney from hex.pm

### PR DESCRIPTION
**Pull request by tverlaan**
I added a rebar.lock as well as created by rebar3. As discussed in #41

### CODE REVIEW

**Comment by tverlaan** [comment]
Is supporting R17 a requirement? I'm not sure what the difference is in deps by using rebar vs rebar3.

**Comment by surik** [comment]
Looks `erlang-idna` needs OTP >= 18 https://github.com/benoitc/erlang-idna/blob/master/rebar.config#L5. Which is weird because `hackney` says: 
`Supported versions of Erlang are R16B03-1, 17.3.4 and above. It is reported to work with R14B04 and R15B03-1.`

**Comment by tverlaan** [comment]
The next hackney release (> 1.8.6) will depend on idna 5.1.0 which doesn't contain minimum OTP version. However next mayor version will only support Erlang >= 19 as per benoitc/hackney#425.

**Comment by surik** [comment]
Then can you update `hackney` to have `idna` 5.1.0?

**Comment by tverlaan** [comment]
Can we now merge this?

**Comment by surik** [comment]
@tverlaan sorry for delay. thank you.

**Pull request merged**
